name: perudo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:

  cloud_firestore: ^4.3.2

  firebase_auth: ^4.2.6

  firebase_core: ^2.5.0

  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0

  flutter_native_splash: ^2.2.16
  flutter_svg: ^2.0.2
  font_awesome_flutter: ^10.3.0

  get: ^4.6.5

  path_provider: ^2.0.12

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/dice1bis.png"
  web: 
    generate: true
    image_path: "assets/icon/dice1bis.png"

flutter_native_splash:
  color: "#12737b"
  image: assets/icon/dice1bis.png
  android_12:
  
    color: "#12737b"
    image: assets/icon/dice1bis.png

flutter:

  uses-material-design: true

  assets: 
    - assets/images/
