// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXtSCe7QRAUSznIwngaCCMZICvONfTRls',
    appId: '1:327357602024:web:99701aba01c9bb45aad15d',
    messagingSenderId: '327357602024',
    projectId: 'perudo-5cd87',
    authDomain: 'perudo-5cd87.firebaseapp.com',
    storageBucket: 'perudo-5cd87.appspot.com',
    measurementId: 'G-DR65S5BBJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdebKXmq5WEdOlonIFK4thfAgqA9railQ',
    appId: '1:327357602024:android:6629d5bf6eba61a2aad15d',
    messagingSenderId: '327357602024',
    projectId: 'perudo-5cd87',
    storageBucket: 'perudo-5cd87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCxMB2h0ZshV4VAe6Nt361hvKJqQQIAss',
    appId: '1:327357602024:ios:870842c0888a470caad15d',
    messagingSenderId: '327357602024',
    projectId: 'perudo-5cd87',
    storageBucket: 'perudo-5cd87.appspot.com',
    iosClientId: '327357602024-s7nhmmvja38hma87krbi8vmhqqpvnbvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.perudo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCxMB2h0ZshV4VAe6Nt361hvKJqQQIAss',
    appId: '1:327357602024:ios:870842c0888a470caad15d',
    messagingSenderId: '327357602024',
    projectId: 'perudo-5cd87',
    storageBucket: 'perudo-5cd87.appspot.com',
    iosClientId: '327357602024-s7nhmmvja38hma87krbi8vmhqqpvnbvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.perudo',
  );
}
