import 'package:get/get.dart';

class TextLang extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'home': 'Home',
          'game': 'Game',
          'settings': 'Settings',
          'perudo': 'Perudo',
          'play': 'Play',
          'how2play': 'How to play',
          'credit': 'Credits',
          'place_left': 'Places left :',
          'needName': 'Your room need to have a name',
          'needPassword': 'Your room need to have a password',
          'roomName': 'Name of the room :',
          'isPublic': 'Is the room public ?',
          'password': 'Password :',
          'numbPlayer': 'Number of players :',
          'numbDice': 'Number of dices for each player :',
          'numbRound': 'Number of round :',
          'isPacoBonus': 'Does the Pacos count as bonuses ?',
          'isCalzaPossible': 'Can we use Calza ?',
          'useDiceDeadCount': 'Show the number of lost dices ?',
          'useDiceCount': 'Show the number of dices each player have ?',
          'yes': 'Yes',
          'no': 'No',
          'createGame': 'Start a game',
          'lang': 'Language :',
          'fr': 'French',
          'en': 'English',
          'name': 'Name :',
          'brightness': 'Application brightness :',
          'system': 'System',
          'light': 'Light',
          'dark': 'Dark',
          'lightColor': 'Light mode color',
          'settingsList': 'Settings : ',
          'noGames': 'No games, create one !',
          'needPlayers': 'There isn\'t enought players to start.',
          'currentNumber': 'Players in the game :',
          'modTryDelete': 'If you quit this game will be deleted, '
              'press for a few second on "Quit" to confirm.',
          'playerTryQuit': 'Press "Quit" for a few second to quit.',
          'quit': 'Quit',
          'start': 'Start',
          'canStart': 'The game can start.',
          'noMove': 'No moves yet, the first players is :',
          'startedTheGame': 'The game begun.',
          'yourTurn': 'It\'s your turn !',
          'chooseBid': '(Out)Bid :',
          'number': 'Number of dices',
          'value': 'Dice value',
          'bid': 'Confirm :',
          'cantBid': 'It i\'snt a outbid !',
          'or': 'Or finelly :',
          'orCalza': 'Or :',
          'calza': 'CALZA',
          'dudo': 'DUDO',
          'gameDontExit': 'This game don\'t exist or has been deleted',
          'wontSave': 'You won\'t be able to save using the web app',
          'userName': 'You should change your name !',
          'useAnyway': 'Continue nevertheless.'
        },
        'fr': {
          'home': 'Accueil',
          'game': 'Jeu',
          'settings': 'Réglages',
          'perudo': 'Pérudo',
          'play': 'Jouer',
          'how2play': 'Comment jouer',
          'credit': 'Crédits',
          'place_left': 'Places restantes :',
          'needName': 'La salle doit avoir un nom',
          'needPassword': 'La salle doit avoir un mot de passe',
          'roomName': 'Nom de la salle :',
          'isPublic': 'La salle est-elle publique ?',
          'password': 'Mot de passe :',
          'numbPlayer': 'Nombre de joueurs :',
          'numbDice': 'Nombre de dés par joueur :',
          'numbRound': 'Nombre de parties :',
          'isPacoBonus': 'Les Pacos comptent-il comme bonus ?',
          'isCalzaPossible': 'Peut-on utiliser le Calzas ?',
          'useDiceDeadCount': 'Montrer le nombre de dés perdus ?',
          'useDiceCount': 'Montrer le nombre de dés de chaque joueur ?',
          'yes': 'Oui',
          'no': 'Non',
          'createGame': 'Créer une partie',
          'lang': 'Language :',
          'fr': 'Français',
          'en': 'Anglais',
          'name': 'Nom :',
          'brightness': 'Luminosité de l\'application :',
          'system': 'Systeme',
          'light': 'Lumineux',
          'dark': 'Sombre',
          'lightColor': 'Couleur du thème lumineux',
          'settingsList': 'Réglages : ',
          'noGames': 'Pas de parties disponnibles, crée en une !',
          'needPlayers': 'Il n\'y a pas assez de joueurs pour commencer',
          'currentNumber': 'Nombre de joueurs actuellement',
          'modTryDelete': 'Si vous quittez cette partie sera supprimer, '
              'appuis longtemps sur le bouton "Quitter" pour confirmer.',
          'playerTryQuit': 'Appuyez longtemps sur '
              'le bouton "Quitter" pour quitter.',
          'quit': 'Quitter',
          'start': 'Commencer',
          'canStart': 'Le jeu peut commencer.',
          'noMove': 'Aucun coup joué, le premier joueur est :',
          'startedTheGame': 'Le jeu a commencer.',
          'yourTurn': 'C\'est à toi de jouer !',
          'chooseBid': '(Sur)Enchéries :',
          'number': 'Nombre de dés',
          'value': 'Valeurs des dés',
          'bid': 'Confirme :',
          'cantBid': 'Ce n\'est pas un surenchère !',
          'or': 'Ou enfin :',
          'orCalza': 'Ou :',
          'calza': 'CALZA',
          'dudo': 'DUDO',
          'gameDontExit': 'La partie n\'existe pas ou à été supprimé',
          'wontSave': 'Les changements ne seront pas enregistré',
          'userName': 'Pensez à changer votre surnom !',
          'useAnyway': 'Continuer quand même.'
        },
      };
}
